[2025-01-14T00:06:22.679+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:06:22.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:06:22.682+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:06:22.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:06:23.387+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:06:23.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:06:23.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:06:23.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.728 seconds
[2025-01-14T00:06:53.624+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:06:53.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:06:53.626+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:06:53.626+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:06:53.904+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:06:53.904+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:06:53.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:06:53.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.294 seconds
[2025-01-14T00:07:23.936+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:07:23.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:07:23.937+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:07:23.937+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:07:24.200+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:07:24.199+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:07:24.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:07:24.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.279 seconds
[2025-01-14T00:07:54.233+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:07:54.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:07:54.235+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:07:54.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:07:54.488+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:07:54.487+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:07:54.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:07:54.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.269 seconds
[2025-01-14T00:08:24.531+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:08:24.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:08:24.533+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:08:24.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:08:24.794+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:08:24.793+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:08:24.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:08:24.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.277 seconds
[2025-01-14T00:08:55.817+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:08:55.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:08:55.819+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:08:55.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:08:56.124+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:08:56.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:08:56.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:08:56.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.323 seconds
[2025-01-14T00:09:26.159+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:09:26.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:09:26.161+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:09:26.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:09:26.432+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:09:26.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:09:26.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:09:26.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.288 seconds
[2025-01-14T00:09:57.414+0000] {processor.py:161} INFO - Started process (PID=458) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:09:57.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:09:57.416+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:09:57.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:09:57.676+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:09:57.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:09:57.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:09:57.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.277 seconds
[2025-01-14T00:10:28.681+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:10:28.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:10:28.683+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:10:28.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:10:28.947+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:10:28.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:10:28.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:10:28.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.281 seconds
[2025-01-14T00:10:59.750+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:10:59.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:10:59.753+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:10:59.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:11:00.025+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:11:00.024+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:11:00.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:11:00.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.290 seconds
[2025-01-14T00:11:31.014+0000] {processor.py:161} INFO - Started process (PID=635) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:11:31.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:11:31.016+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:11:31.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:11:31.288+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:11:31.287+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:11:31.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:11:31.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.289 seconds
[2025-01-14T00:12:02.265+0000] {processor.py:161} INFO - Started process (PID=694) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:12:02.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:12:02.267+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:12:02.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:12:02.526+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:12:02.526+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:12:02.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:12:02.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.276 seconds
[2025-01-14T00:12:33.484+0000] {processor.py:161} INFO - Started process (PID=753) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:12:33.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:12:33.486+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:12:33.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:12:33.753+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:12:33.753+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:12:33.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:12:33.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.284 seconds
[2025-01-14T00:13:04.584+0000] {processor.py:161} INFO - Started process (PID=812) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:13:04.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:13:04.585+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:13:04.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:13:04.862+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:13:04.861+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:13:04.862+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:13:04.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.292 seconds
[2025-01-14T00:13:35.657+0000] {processor.py:161} INFO - Started process (PID=871) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:13:35.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:13:35.659+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:13:35.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:13:35.935+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:13:35.934+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:13:35.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:13:35.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.293 seconds
[2025-01-14T00:14:06.002+0000] {processor.py:161} INFO - Started process (PID=930) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:14:06.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:14:06.004+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:14:06.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:14:06.298+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:14:06.298+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:14:06.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:14:06.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.312 seconds
[2025-01-14T00:14:37.299+0000] {processor.py:161} INFO - Started process (PID=989) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:14:37.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:14:37.302+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:14:37.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:14:37.583+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:14:37.583+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:14:37.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:14:37.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.298 seconds
[2025-01-14T00:15:08.490+0000] {processor.py:161} INFO - Started process (PID=1048) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:15:08.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:15:08.492+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:15:08.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:15:08.795+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:15:08.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:15:08.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:15:08.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.321 seconds
[2025-01-14T00:15:39.755+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:15:39.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:15:39.757+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:15:39.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:15:40.027+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:15:40.026+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:15:40.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:15:40.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.287 seconds
[2025-01-14T00:16:11.004+0000] {processor.py:161} INFO - Started process (PID=1166) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:16:11.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:16:11.006+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:16:11.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:16:11.336+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:16:11.335+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:16:11.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:16:11.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.347 seconds
[2025-01-14T00:16:42.218+0000] {processor.py:161} INFO - Started process (PID=1225) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:16:42.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:16:42.220+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:16:42.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:16:42.476+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:16:42.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:16:42.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:16:42.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.272 seconds
[2025-01-14T00:17:13.389+0000] {processor.py:161} INFO - Started process (PID=1290) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:17:13.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:17:13.392+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:17:13.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:17:13.671+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:17:13.671+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:17:13.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:17:13.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.296 seconds
[2025-01-14T00:17:44.521+0000] {processor.py:161} INFO - Started process (PID=1349) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:17:44.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:17:44.523+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:17:44.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:17:44.799+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:17:44.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:17:44.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:17:44.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.292 seconds
[2025-01-14T00:18:14.837+0000] {processor.py:161} INFO - Started process (PID=1408) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:18:14.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:18:14.839+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:18:14.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:18:15.118+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:18:15.118+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:18:15.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:18:15.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.296 seconds
[2025-01-14T00:18:46.100+0000] {processor.py:161} INFO - Started process (PID=1467) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:18:46.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:18:46.102+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:18:46.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:18:46.372+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:18:46.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:18:46.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:18:46.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.286 seconds
[2025-01-14T00:19:17.303+0000] {processor.py:161} INFO - Started process (PID=1526) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:19:17.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:19:17.305+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:19:17.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:19:17.567+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:19:17.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:19:17.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:19:17.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.280 seconds
[2025-01-14T00:19:48.507+0000] {processor.py:161} INFO - Started process (PID=1585) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:19:48.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:19:48.509+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:19:48.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:19:48.819+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:19:48.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:19:48.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:19:48.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.329 seconds
[2025-01-14T00:20:19.798+0000] {processor.py:161} INFO - Started process (PID=1644) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:20:19.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:20:19.800+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:20:19.800+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:20:20.236+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:20:20.235+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:20:20.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:20:20.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.456 seconds
[2025-01-14T00:20:50.508+0000] {processor.py:161} INFO - Started process (PID=1703) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:20:50.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:20:50.510+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:20:50.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:20:50.784+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:20:50.783+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:20:50.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:20:50.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.291 seconds
[2025-01-14T00:21:21.617+0000] {processor.py:161} INFO - Started process (PID=1762) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:21:21.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:21:21.619+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:21:21.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:21:21.882+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:21:21.881+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:21:21.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:21:21.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.280 seconds
[2025-01-14T00:21:52.817+0000] {processor.py:161} INFO - Started process (PID=1821) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:21:52.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:21:52.819+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:21:52.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:21:53.110+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:21:53.109+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:21:53.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:21:53.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.308 seconds
[2025-01-14T00:22:23.989+0000] {processor.py:161} INFO - Started process (PID=1880) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:22:23.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:22:23.991+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:22:23.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:22:24.299+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:22:24.298+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:22:24.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:22:24.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.328 seconds
[2025-01-14T00:22:55.178+0000] {processor.py:161} INFO - Started process (PID=1939) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:22:55.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:22:55.180+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:22:55.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:22:55.448+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:22:55.447+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:22:55.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:22:55.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.285 seconds
[2025-01-14T00:23:26.292+0000] {processor.py:161} INFO - Started process (PID=1998) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:23:26.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:23:26.293+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:23:26.293+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:23:26.590+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:23:26.589+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:23:26.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:23:26.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.313 seconds
[2025-01-14T00:23:57.518+0000] {processor.py:161} INFO - Started process (PID=2057) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:23:57.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:23:57.521+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:23:57.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:23:57.814+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:23:57.813+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:23:57.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:23:57.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.310 seconds
[2025-01-14T00:24:28.591+0000] {processor.py:161} INFO - Started process (PID=2116) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:24:28.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:24:28.593+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:24:28.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:24:28.866+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:24:28.865+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:24:28.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:24:28.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.288 seconds
[2025-01-14T00:24:58.911+0000] {processor.py:161} INFO - Started process (PID=2175) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:24:58.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:24:58.913+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:24:58.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:24:59.217+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:24:59.216+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:24:59.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:24:59.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.321 seconds
[2025-01-14T00:25:30.020+0000] {processor.py:161} INFO - Started process (PID=2234) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:25:30.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:25:30.022+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:25:30.021+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:25:30.283+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:25:30.282+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:25:30.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:25:30.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.279 seconds
[2025-01-14T00:26:01.271+0000] {processor.py:161} INFO - Started process (PID=2293) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:26:01.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:26:01.272+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:26:01.272+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:26:01.550+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:26:01.549+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:26:01.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:26:01.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.293 seconds
[2025-01-14T00:26:31.795+0000] {processor.py:161} INFO - Started process (PID=2352) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:26:31.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:26:31.799+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:26:31.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:26:32.081+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:26:32.081+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:26:32.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:26:32.094+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.302 seconds
[2025-01-14T00:27:02.667+0000] {processor.py:161} INFO - Started process (PID=2411) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:27:02.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:27:02.669+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:27:02.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:27:02.955+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:27:02.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:27:02.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:27:02.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.302 seconds
[2025-01-14T00:27:33.480+0000] {processor.py:161} INFO - Started process (PID=2470) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:27:33.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:27:33.482+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:27:33.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:27:33.759+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:27:33.759+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:27:33.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:27:33.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.295 seconds
[2025-01-14T00:28:03.975+0000] {processor.py:161} INFO - Started process (PID=2529) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:28:03.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:28:03.977+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:28:03.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:28:04.283+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:28:04.282+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:28:04.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:28:04.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.322 seconds
[2025-01-14T00:28:34.415+0000] {processor.py:161} INFO - Started process (PID=2588) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:28:34.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:28:34.416+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:28:34.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:28:34.715+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:28:34.714+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:28:34.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:28:34.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.318 seconds
[2025-01-14T00:29:04.772+0000] {processor.py:161} INFO - Started process (PID=2647) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:29:04.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:29:04.774+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:29:04.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:29:05.102+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:29:05.101+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:29:05.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:29:05.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.346 seconds
[2025-01-14T00:29:35.203+0000] {processor.py:161} INFO - Started process (PID=2706) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:29:35.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:29:35.205+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:29:35.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:29:35.363+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:29:35.363+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:29:35.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:29:35.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.176 seconds
[2025-01-14T00:30:05.636+0000] {processor.py:161} INFO - Started process (PID=2765) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:30:05.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:30:05.638+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:30:05.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:30:05.798+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:30:05.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:30:05.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:30:05.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.179 seconds
[2025-01-14T00:30:36.411+0000] {processor.py:161} INFO - Started process (PID=2824) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:30:36.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:30:36.415+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:30:36.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:30:36.595+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:30:36.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:30:36.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:30:36.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.205 seconds
[2025-01-14T00:31:07.127+0000] {processor.py:161} INFO - Started process (PID=2883) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:31:07.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:31:07.129+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:31:07.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:31:07.289+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:31:07.288+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:31:07.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:31:07.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.177 seconds
[2025-01-14T00:31:37.985+0000] {processor.py:161} INFO - Started process (PID=2942) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:31:37.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:31:37.986+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:31:37.986+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:31:38.149+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:31:38.148+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:31:38.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:31:38.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.181 seconds
[2025-01-14T00:32:08.764+0000] {processor.py:161} INFO - Started process (PID=3001) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:32:08.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:32:08.766+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:32:08.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:32:08.953+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:32:08.952+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:32:08.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:32:09.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.304 seconds
[2025-01-14T00:32:39.850+0000] {processor.py:161} INFO - Started process (PID=3060) to work on /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:32:39.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_ml_dag.py for tasks to queue
[2025-01-14T00:32:39.852+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:32:39.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:32:40.006+0000] {logging_mixin.py:188} INFO - [2025-01-14T00:32:40.005+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_ml_dag.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-14T00:32:40.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_ml_dag.py
[2025-01-14T00:32:40.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_ml_dag.py took 0.171 seconds
