[2025-01-13T22:13:56.197+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_pipeline.save_to_postgres manual__2025-01-13T22:13:53.094517+00:00 [queued]>
[2025-01-13T22:13:56.201+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_pipeline.save_to_postgres manual__2025-01-13T22:13:53.094517+00:00 [queued]>
[2025-01-13T22:13:56.201+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-13T22:13:56.211+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2025-01-13 22:13:53.094517+00:00
[2025-01-13T22:13:56.214+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2025-01-13T22:13:56.216+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_pipeline', 'save_to_postgres', 'manual__2025-01-13T22:13:53.094517+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpdl_bbv7a']
[2025-01-13T22:13:56.217+0000] {standard_task_runner.py:88} INFO - Job 71: Subtask save_to_postgres
[2025-01-13T22:13:56.245+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_pipeline.save_to_postgres manual__2025-01-13T22:13:53.094517+00:00 [running]> on host 4ba0c249c602
[2025-01-13T22:13:56.289+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_pipeline' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T22:13:53.094517+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T22:13:53.094517+00:00'
[2025-01-13T22:13:56.290+0000] {logging_mixin.py:188} INFO - Saving data to PostgreSQL...
[2025-01-13T22:13:56.295+0000] {base.py:83} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2025-01-13T22:13:56.324+0000] {logging_mixin.py:188} INFO - Data saved to PostgreSQL.
[2025-01-13T22:13:56.325+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-13T22:13:56.331+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_pipeline, task_id=save_to_postgres, execution_date=20250113T221353, start_date=20250113T221356, end_date=20250113T221356
[2025-01-13T22:13:56.348+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-13T22:13:56.359+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
